// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc319.backOnTrack.commands;

import edu.wpi.first.wpilibj.command.Command;

import org.usfirst.frc319.backOnTrack.Robot;

/**
 *
 */
public class  JoyStickTankDrive extends Command {

    public JoyStickTankDrive() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
    	
        requires(Robot.driveTrain);
    }
    protected void initialize() {
    }
    
    protected void execute() {
    double leftValue = Robot.oi.xboxController1.getRawAxis(1);
	double rightValue = Robot.oi.xboxController1.getRawAxis(5);
	
	Robot.driveTrain.tankDrive(-leftValue, -rightValue);
	System.out.println(+Robot.driveTrain.leftSpeed());
	//uses driveTrain and is combined with the analogs on the controller
    }
   
    protected boolean isFinished() {
        return false;
    }

    protected void end() {
    }

    protected void interrupted() {
    }
}
